// LOGIN
export const LOGING_USER = 'LOGING_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_LOGOUT = 'LOGIN_USER_LOGOUT';

// CUSTOMERS
export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING';
export const CUSTOMERS_LOAD_SUCCESS = 'CUSTOMERS_LOAD_SUCCESS';
export const CUSTOMERS_LOAD_ERROR = 'CUSTOMERS_LOAD_ERROR';

// SHOP
export const SHOP_LOADING = 'SHOP_LOADING';
export const SHOP_LOAD_SUCCESS = 'SHOP_LOAD_SUCCESS';
export const SHOP_LOAD_ERROR = 'SHOP_LOAD_ERROR';

